### ISSUE TITLE
Explicit license file?

### ISSUE THREAD

**Issue by daboross** [ThunderMikey/pid_fan_controller#1]
Hi!

I really like this project and the idea behind it. I'd like to fork and make some personal modifications, but I'm a bit unsure about publishing them on github.

Specifically, while PKGBUILD lists `gpl3` as the license, there's no LICENSE file (nor explicit copyright text mentioning the project name / author name). If it wouldn't be too much trouble, could you add an explicit LICENSE file to clear up the exact license this is under?

Thanks!

**Comment by ThunderMikey** [comment]
Hi daboross,

Thank you for your interest in my project. You are correct that I want it to be under GPLv3. Now that I have added the license file, feel free to make modifications, and I look forward to what you come up with!

**Comment by daboross** [comment]
Thank you!

My plans aren't anything really that exciting, mostly just tweaking things for personal use and messing with stuff. I really like the PID idea, and I think this is a pretty nice execution of that!
